<a href="https://colab.research.google.com/github/husnainsr/Pytorch-Learning/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Goal is to learn Basics of Pytorch**


*   Types
*   Operations



In [3]:
import torch
import numpy as np

# How simple List works in python


In [11]:
my_list = [1,22,34,12,14,15,15]
print(my_list)

[1, 22, 34, 12, 14, 15, 15]


# How List works in Numpy

In [13]:
#Lets create a random array

my_list = np.random.rand(4)
print(my_list)

# moving on to 2D list
#r and c
my_list = np.random.rand(4,3)
print(my_list)

# by default numpy stores float64
print(my_list.dtype)



[0.9265576  0.57442202 0.67186719 0.54178361]
[[0.7993339  0.82170648 0.4084114 ]
 [0.63002051 0.16240619 0.44093258]
 [0.13998578 0.09457141 0.20602732]
 [0.58564028 0.53892969 0.7787529 ]]
float64


# Lets see How tesnors works

In [18]:
#lets create simple 1d tensor
my_list = torch.randn(4)
print(my_list)

#2d tensor
my_list = torch.randn(4,3)
print(my_list)

# by default tensor stores float32
print(my_list.dtype)

tensor([-1.3462, -0.0127,  0.6361, -1.0858])
tensor([[ 2.3158, -1.3088, -1.1111],
        [-0.3252, -1.1304, -0.1450],
        [-0.1310, -0.1186, -0.5844],
        [-0.4809,  0.1591, -0.3992]])
torch.float32


In [20]:
# what about 3D tensors? Lets give it a try
# Number of matrix then rows and then columns
list_3D= torch.randn(2,4,3)
print(list_3D)

tensor([[[ 0.6474,  2.4481, -0.2953],
         [ 1.2528, -0.1849,  1.2597],
         [-0.6689, -0.7217, -0.0068],
         [ 0.3288,  0.4718, -0.2877]],

        [[ 0.7891,  0.9494,  0.8459],
         [-0.5934,  0.1285, -0.5021],
         [ 0.0660, -0.4156, -0.8699],
         [ 0.2717,  0.6079, -0.6541]]])


## Tensors with Numpy

In [26]:
# Can we create tensors out of numpy?
np1 = np.random.rand(4,3)
print("Numpy Array")
print(np1)

#Notice how numpy uses default float64 and when we converted to tensors it remains the default dtype
tensor1= torch.tensor(np1)
print("Tensor Array")
print(tensor1)

Numpy Array
[[0.28481391 0.78300792 0.06390192]
 [0.60295664 0.41884119 0.42766781]
 [0.02865075 0.86757039 0.47959685]
 [0.14255954 0.38366281 0.25611061]]
Tensor Array
tensor([[0.2848, 0.7830, 0.0639],
        [0.6030, 0.4188, 0.4277],
        [0.0287, 0.8676, 0.4796],
        [0.1426, 0.3837, 0.2561]], dtype=torch.float64)
