<a href="https://colab.research.google.com/github/husnainsr/Pytorch-Learning/blob/main/Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [9]:
t1 = torch.tensor([1,2,3,4,5,6])
t2 = torch.tensor([1,1,1,1,1,1])
t3 = torch.tensor([2,2,2,2,2,2])

In [23]:
# Simple Add in two ways
print("Addition")
print(t1+t2)
print(torch.add(t1,t2))
print(t1.add(t2))

print("Subtraction")
print(t1-t2)
print(torch.subtract(t1,t2))
print(t1.subtract(t2))


Addition
tensor([2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7])
Subtraction
tensor([0, 1, 2, 3, 4, 5])
tensor([0, 1, 2, 3, 4, 5])
tensor([0, 1, 2, 3, 4, 5])


In [24]:
#Multiplication with each value
print(t1*t3)
print(torch.mul(t1,t3))
print(t1.mul(t3))

tensor([ 2,  4,  6,  8, 10, 12])
tensor([ 2,  4,  6,  8, 10, 12])
tensor([ 2,  4,  6,  8, 10, 12])


In [14]:
#Divison
print(t1/t3)
print(torch.divide(t1,t3))

tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000])
tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000])


In [18]:
#Modulus
print(t1%t3)

#or we can use remainder function it is the same thing
print(torch.remainder(t1,t3))

tensor([1, 0, 1, 0, 1, 0])
tensor([1, 0, 1, 0, 1, 0])


In [22]:
#Exponents or Powers
print(t1 **t3)
print(torch.pow(t1,t3))


tensor([ 1,  4,  9, 16, 25, 36])
tensor([ 1,  4,  9, 16, 25, 36])


In [26]:
#there are two ways to assign the tensor value basic way
# t1 = t1 + t2
# or we can use "_" to assign the value

print(t1.add_(t2))

tensor([2, 3, 4, 5, 6, 7])
